// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import { defineConfig } from "prisma/config";
import * as dotenv from "dotenv";
dotenv.config();

const host = process.env.DB_HOST || "localhost";
const port = process.env.DB_PORT || "5432";
const user = process.env.DB_USER || "postgres";
const password = process.env.DB_PASSWORD || "";
const database = process.env.DB_NAME || "postgres";
const schema = process.env.DB_SCHEMA || "public";

const DATABASE_URL = `postgresql://${user}:${password}@${host}:${port}/${database}?schema=${schema}`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: DATABASE_URL,
  },
});
