
const ACCESS_SECRET_KEY = process.env.SECRET_KEY || 'v3W7MYVJhTV8KE6ZPZ-CkpaieHyY2xQn2ABhDuGZN2G6MTmRaiafqFDR_Lbw';
const REFRESH_SECRET_KEY = process.env.REFRESH_SECRET_KEY || 'CkpaieHyY2xQn2ABhDuGZN2G6MTmRaiafqFDR_LbwVJhTV8K';


const ACCESS_TOKEN_EXPIRATION_TIME = '1h';
const REFRESH_TOKEN_EXPIRATION_TIME = '30d';
const ACCESS_TOKEN_TIME = 60; // minutes
const REFRESH_TOKEN_TIME = 30; // days

export { 
    ACCESS_SECRET_KEY, 
    REFRESH_SECRET_KEY, 
    REFRESH_TOKEN_EXPIRATION_TIME, 
    ACCESS_TOKEN_EXPIRATION_TIME, 
    ACCESS_TOKEN_TIME, 
    REFRESH_TOKEN_TIME 
};