import type { Cell } from "../types/types";

export const cells: Cell[] = [
     { id: 0, type: "corner", name: "Старт", isBuying: false },
    {
        id: 1,
        type: "property",
        name: "Арбат",
        price: 60,
        rent: 10,
        color: "brown",
        owner: "blue",
        isBuying: true,
    },
    { id: 2, type: "chance", name: "Шанс", isBuying: false },
    {
        id: 3,
        type: "property",
        name: "Тверская",
        price: 60,
        rent: 10,
        color: "brown",
        owner: "blue",
        isBuying: true,
    },
    { id: 4, type: "tax", name: "Налог", isBuying: false },
    {
        id: 5,
        type: "railroad",
        name: "Вокзал",
        price: 200,
        rent: 25,
        owner: "blue",
        isBuying: true,
    },
    {
        id: 6,
        type: "property",
        name: "Невский",
        price: 100,
        rent: 15,
        color: "lightblue",
        isBuying: true,
    },
    { id: 7, type: "chance", name: "Шанс", isBuying: false },
    {
        id: 8,
        type: "property",
        name: "Садовое",
        price: 100,
        rent: 15,
        color: "lightblue",
        owner: "yellow",
        isBuying: true,
    },
    {
        id: 9,
        type: "property",
        name: "Кутузовский",
        price: 120,
        rent: 18,
        color: "lightblue",
        owner: "green",
        isBuying: true,
    },
    { id: 10, type: "corner", name: "Тюрьма", isBuying: false },
    {
        id: 11,
        type: "property",
        name: "Ленинградский",
        price: 140,
        rent: 20,
        color: "pink",
        isBuying: true,
    },
    { id: 12, type: "utility", name: "Электростанция", price: 150, rent: 10, isBuying: true },
    {
        id: 13,
        type: "property",
        name: "Рублёвка",
        price: 140,
        rent: 20,
        color: "pink",
        owner: "red",
        isBuying: true,
    },
    {
        id: 14,
        type: "property",
        name: "Патриаршие",
        price: 160,
        rent: 22,
        color: "pink",
        isBuying: true,
    },
    {
        id: 15,
        type: "railroad",
        name: "Аэропорт",
        price: 200,
        rent: 25,
        owner: "red",
        isBuying: true,
    },
    {
        id: 16,
        type: "property",
        name: "Бауманская",
        price: 180,
        rent: 25,
        color: "orange",
        isBuying: true,
    },
    { id: 17, type: "chance", name: "Шанс", isBuying: false },
    {
        id: 18,
        type: "property",
        name: "Таганская",
        price: 180,
        rent: 25,
        color: "orange",
        isBuying: true,
    },
    {
        id: 19,
        type: "property",
        name: "Красная площадь",
        price: 200,
        rent: 28,
        color: "orange",
        isBuying: true,
    },
    { id: 20, type: "corner", name: "Парковка", isBuying: false },
    {
        id: 21,
        type: "property",
        name: "Петровка",
        price: 220,
        rent: 30,
        color: "red",
        owner: "green",
        isBuying: true,
    },
    { id: 22, type: "chance", name: "Шанс", isBuying: false },
    {
        id: 23,
        type: "property",
        name: "Остоженка",
        price: 220,
        rent: 30,
        color: "red",
        isBuying: true,
    },
    {
        id: 24,
        type: "property",
        name: "Пречистенка",
        price: 240,
        rent: 32,
        color: "red",
        owner: "green",
        isBuying: true,
    },
    { id: 25, type: "railroad", name: "Метро", price: 200, rent: 25, isBuying: true },
    {
        id: 26,
        type: "property",
        name: "Мясницкая",
        price: 260,
        rent: 35,
        color: "yellow",
        isBuying: true,
    },
    {
        id: 27,
        type: "property",
        name: "Покровка",
        price: 260,
        rent: 35,
        color: "yellow",
        isBuying: true,
    },
    { id: 28, type: "utility", name: "Водоканал", price: 150, rent: 10, isBuying: true },
    {
        id: 29,
        type: "property",
        name: "Лубянка",
        price: 280,
        rent: 38,
        color: "yellow",
        isBuying: true,
    },
    { id: 30, type: "corner", name: "В тюрьму", isBuying: false },
    {
        id: 31,
        type: "property",
        name: "Ильинка",
        price: 300,
        rent: 40,
        color: "green",
        owner: "green",
        isBuying: true,
    },
    {
        id: 32,
        type: "property",
        name: "Варварка",
        price: 300,
        rent: 40,
        color: "green",
        isBuying: true,
    },
    { id: 33, type: "chance", name: "Шанс", isBuying: false },
    {
        id: 34,
        type: "property",
        name: "Никольская",
        price: 320,
        rent: 42,
        color: "green",
        isBuying: true,
    },
    { id: 35, type: "railroad", name: "Порт", price: 200, rent: 25, isBuying: true },
    { id: 36, type: "chance", name: "Шанс", isBuying: false },
    {
        id: 37,
        type: "property",
        name: "Воздвиженка",
        price: 350,
        rent: 50,
        color: "darkblue",
        isBuying: true,
    },
    { id: 38, type: "tax", name: "Налог", isBuying: false },
    {
        id: 39,
        type: "property",
        name: "Моховая",
        price: 400,
        rent: 60,
        color: "darkblue",
        isBuying: true,
    },
  ];
