import type { Ceil } from "../types/types";

export const cells: Ceil[] = [
  { id: 0, type: "CORNER", name: "Старт", isBuying: false },
  {
    id: 1,
    type: "PROPERTY",
    name: "Арбат",
    price: 60,
    rent: 20,
    color: "brown",
    isBuying: true,
    housePrice: 50,
    hotelPrice: 100,
  },
  { id: 2, type: "CHANCE", name: "Шанс", isBuying: false },
  {
    id: 3,
    type: "PROPERTY",
    name: "Тверская",
    price: 60,
    rent: 20,
    color: "brown",
    isBuying: true,
    housePrice: 50,
    hotelPrice: 100,
  },
  { id: 4, type: "TAX", name: "Налог", isBuying: false },
  {
    id: 5,
    type: "RAILROAD",
    name: "Вокзал",
    price: 200,
    rent: 50,
    isBuying: true,
    housePrice: 50,
    hotelPrice: 100,
  },
  {
    id: 6,
    type: "PROPERTY",
    name: "Невский",
    price: 100,
    rent: 30,
    color: "lightblue",
    isBuying: true,
    housePrice: 50,
    hotelPrice: 100,
  },
  { id: 7, type: "CHANCE", name: "Шанс", isBuying: false },
  {
    id: 8,
    type: "PROPERTY",
    name: "Садовое",
    price: 100,
    rent: 30,
    color: "lightblue",
    isBuying: true,
    housePrice: 50,
    hotelPrice: 100,
  },
  {
    id: 9,
    type: "PROPERTY",
    name: "Кутузовский",
    price: 120,
    rent: 36,
    color: "lightblue",
    isBuying: true,
    housePrice: 50,
    hotelPrice: 100,
  },
  { id: 10, type: "CORNER", name: "Тюрьма", isBuying: false },
  {
    id: 11,
    type: "PROPERTY",
    name: "Ленинградский",
    price: 140,
    rent: 40,
    color: "pink",
    isBuying: true,
    housePrice: 100,
    hotelPrice: 150,
  },
  {
    id: 12,
    type: "UTILITY",
    name: "Электростанция",
    price: 150,
    rent: 20,
    isBuying: true,
    housePrice: 0,
    hotelPrice: 0,
  },
  {
    id: 13,
    type: "PROPERTY",
    name: "Рублёвка",
    price: 140,
    rent: 40,
    color: "pink",
    isBuying: true,
    housePrice: 100,
    hotelPrice: 150,
  },
  {
    id: 14,
    type: "PROPERTY",
    name: "Патриаршие",
    price: 160,
    rent: 44,
    color: "pink",
    isBuying: true,
    housePrice: 100,
    hotelPrice: 150,
  },
  {
    id: 15,
    type: "RAILROAD",
    name: "Аэропорт",
    price: 200,
    rent: 50,
    isBuying: true,
    housePrice: 100,
    hotelPrice: 150,
  },
  {
    id: 16,
    type: "PROPERTY",
    name: "Бауманская",
    price: 180,
    rent: 50,
    color: "orange",
    isBuying: true,
    housePrice: 100,
    hotelPrice: 150,
  },
  { id: 17, type: "CHANCE", name: "Шанс", isBuying: false },
  {
    id: 18,
    type: "PROPERTY",
    name: "Таганская",
    price: 180,
    rent: 50,
    color: "orange",
    isBuying: true,
    housePrice: 100,
    hotelPrice: 150,
  },
  {
    id: 19,
    type: "PROPERTY",
    name: "Красная площадь",
    price: 200,
    rent: 56,
    color: "orange",
    isBuying: true,
    housePrice: 100,
    hotelPrice: 150,
  },
  { id: 20, type: "CORNER", name: "Парковка", isBuying: false },
  {
    id: 21,
    type: "PROPERTY",
    name: "Петровка",
    price: 220,
    rent: 60,
    color: "red",
    isBuying: true,
    housePrice: 150,
    hotelPrice: 200,
  },
  { id: 22, type: "CHANCE", name: "Шанс", isBuying: false },
  {
    id: 23,
    type: "PROPERTY",
    name: "Остоженка",
    price: 220,
    rent: 60,
    color: "red",
    isBuying: true,
    housePrice: 150,
    hotelPrice: 200,
  },
  {
    id: 24,
    type: "PROPERTY",
    name: "Пречистенка",
    price: 240,
    rent: 64,
    color: "red",
    isBuying: true,
    housePrice: 150,
    hotelPrice: 200,
  },
  {
    id: 25,
    type: "RAILROAD",
    name: "Метро",
    price: 200,
    rent: 50,
    isBuying: true,
    housePrice: 150,
    hotelPrice: 200,
  },
  {
    id: 26,
    type: "PROPERTY",
    name: "Мясницкая",
    price: 260,
    rent: 70,
    color: "yellow",
    isBuying: true,
    housePrice: 150,
    hotelPrice: 200,
  },
  {
    id: 27,
    type: "PROPERTY",
    name: "Покровка",
    price: 260,
    rent: 70,
    color: "yellow",
    isBuying: true,
    housePrice: 150,
    hotelPrice: 200,
  },
  {
    id: 28,
    type: "UTILITY",
    name: "Водоканал",
    price: 150,
    rent: 20,
    isBuying: true,
    housePrice: 0,
    hotelPrice: 0,
  },
  {
    id: 29,
    type: "PROPERTY",
    name: "Лубянка",
    price: 280,
    rent: 76,
    color: "yellow",
    isBuying: true,
    housePrice: 150,
    hotelPrice: 200,
  },
  { id: 30, type: "CORNER", name: "В тюрьму", isBuying: false },
  {
    id: 31,
    type: "PROPERTY",
    name: "Ильинка",
    price: 300,
    rent: 80,
    color: "green",
    isBuying: true,
    housePrice: 200,
    hotelPrice: 250,
  },
  {
    id: 32,
    type: "PROPERTY",
    name: "Варварка",
    price: 300,
    rent: 80,
    color: "green",
    isBuying: true,
    housePrice: 200,
    hotelPrice: 250,
  },
  { id: 33, type: "CHANCE", name: "Шанс", isBuying: false },
  {
    id: 34,
    type: "PROPERTY",
    name: "Никольская",
    price: 320,
    rent: 84,
    color: "green",
    isBuying: true,
    housePrice: 200,
    hotelPrice: 250,
  },
  {
    id: 35,
    type: "RAILROAD",
    name: "Порт",
    price: 200,
    rent: 50,
    isBuying: true,
    housePrice: 200,
    hotelPrice: 250,
  },
  { id: 36, type: "CHANCE", name: "Шанс", isBuying: false },
  {
    id: 37,
    type: "PROPERTY",
    name: "Воздвиженка",
    price: 350,
    rent: 100,
    color: "darkblue",
    isBuying: true,
    housePrice: 200,
    hotelPrice: 250,
  },
  { id: 38, type: "TAX", name: "Налог", isBuying: false },
  {
    id: 39,
    type: "PROPERTY",
    name: "Моховая",
    price: 400,
    rent: 120,
    color: "darkblue",
    isBuying: true,
    housePrice: 200,
    hotelPrice: 250,
  },
];
